FROM ubuntu
LABEL description="this image is rapsberry pi ubuntu cross compilation environment, which installed necessary tool chain. Also with build azure iot sdks c."

#those packages are necessary for building azure iot sdk
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    libcurl4-openssl-dev \
    libssl-dev \
    make \
    pkg-config \
    sshpass \
    uuid-dev \
    valgrind

RUN git clone https://github.com/yungez/rpitools.git
ENV SYSROOT ${PWD}/rpitools/raspbian-jessie-sysroot
ENV CC ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
ENV CXX ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++

COPY toolchain.cmake /toolchain.cmake

# build azure iot sdks
RUN git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git
RUN /azure-iot-sdk-c/build_all/linux/build.sh --toolchain-file /toolchain.cmake
ENV AZURE_IOT_SDK /azure-iot-sdk-c

# copy build script
COPY index.sh /index.sh
COPY deploy.sh /deploy.sh
COPY build.sh /build.sh