FROM ubuntu
LABEL description="This image is a cross compilation environment for Raspberry Pi C, which includes the cross compiler and the sysroot of Raspbian."

#those packages are necessary for building azure iot sdk
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    debootstrap \
    git \
    nodejs \
    npm \
    qemu-user-static


COPY init.sh /init.sh
ENV SYSROOT /root/rpi/chroot-raspbian-armhf


RUN git clone https://github.com/raspberrypi/tools.git /tools && mv /tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64 /gcc-linaro-arm-linux-gnueabihf-raspbian-x64 && rm -rf /tools
ENV CC /gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
ENV CXX /gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++


COPY build.sh /build.sh
COPY toolchain.cmake /toolchain.cmake


# bi
ENV DEVICETYPE raspberrypi
ENV TAG latest

COPY ./bi/ /bi
RUN cd bi/ && npm install