FROM ubuntu
LABEL description="this image is rapsberry pi ubuntu cross compilation environment, which installed necessary tool chain. Also with build azure iot sdks c."

#those packages are necessary for building azure iot sdk
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    debootstrap \
    git \
    nodejs \
    npm \
    qemu-user-static

ENV SYSROOT /root/rpi/chroot-raspbian-armhf


RUN git clone https://github.com/yungez/rpitools.git
ENV CC ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
ENV CXX ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++


COPY init.sh /init.sh

COPY build.sh /build.sh
COPY toolchain.cmake /toolchain.cmake


# bi
ENV DEVICETYPE raspberrypi
ENV TAG latest

COPY ./bi/ /bi
RUN cd bi/ && npm install